//
// Test Bench Module CatRecognizer_lib.NeuronCalculator_tester.NeuronCalculator_tester
//
// Created:
//          by - amitb.UNKNOWN (DESKTOP-GIFQ7HQ)
//          at - 19:30:40 21/11/2018
//
// Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
//
`resetall
`timescale 1ns/10ps
module NeuronCalculator_tester (x,
                                b,
                                w,
                                clock,
                                reset,
                                enable,
                                get_result,
                                out
                               );

// Local declarations

parameter DATA_WIDTH = 24;
parameter Addr_Depth = 12;
parameter Weight_Percision = 5;


output x;
output b;
output w;
output clock;
output reset;
output enable;
output get_result;
input  out;

reg [DATA_WIDTH - 1:0] x;
wire [DATA_WIDTH - 1:0] b;
reg [3*Weight_Percision - 1:0] w;
reg                    clock;
reg                    reset;
reg                    enable;
wire                    get_result;
wire                    out;


initial begin
    clock <= 1'b0;
	enable <= 1'b1;
	reset <= 1'b1;
	#10 reset <= 1'b0;
	#40 reset <= 1'b1;
	#10 reset <= 1'b0;
    //rst <= 1'b0;
end

initial begin forever
    #5 clock = ~clock;
end

initial begin
   
   x <= 24'h030303;
   w <= 15'b111111111111111;

end

endmodule // NeuronCalculator_tester


