//
// Test Bench Module CatRecognizer_lib.RegisterFile_tb.RegisterFile_tester
//
// Created:
//          by - amitb.UNKNOWN (DESKTOP-GIFQ7HQ)
//          at - 16:05:52 17/11/2018
//
// Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
//
`resetall
`timescale 1ns/10ps

module RegisterFile_tb;

// Local declarations
parameter Amba_Word = 24;
parameter Addr_Depth = 12;

// Internal signal declarations
logic                         clock;
wire  [Addr_Depth - 1:0] address;
logic                         en_write;
logic                         en_read;
wire  [Amba_Word - 1:0]       data_in;
wire  [Amba_Word - 1:0]       data_out;
//wire  [(2**Addr_Depth)*24-1:0]      temp_data_out;


RegisterFile #(Amba_Word,Addr_Depth) rftestRegisterFile(
   .clock    (clock),
   .address  (address),
   .en_write (en_write),
   .en_read  (en_read),
   .data_in  (data_in),
   .data_out (data_out)
  // .temp_data_out(temp_data_out)
);

RegisterFile_tester #(Amba_Word,Addr_Depth) rftestRegisterFile_tester(
   .clock    (clock),
   .address  (address),
   .en_write (en_write),
   .en_read  (en_read),
   .data_in  (data_in),
   .data_out (data_out)
  // .temp_data_out(temp_data_out)
);

endmodule // RegisterFile_tb


